name: Test
on:
  pull_request:

env:
  DOCKER_BUILDKIT: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ github.token }}
      - name: Cache register
        id: cache
        uses: actions/cache@v3.2.3
        with:
          path: /tmp/odoo.tar
          key: odoo-${{ runner.os }}-${{ hashFiles('**/Dockerfile', '**/requirements.txt') }}
      - name: Set up Docker Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./odoo
          file: ./odoo/Dockerfile
          tags: odoo-core
          outputs: type=docker,dest=/tmp/odoo.tar
      - name: Load image
        run: |
          docker load --input /tmp/odoo.tar
      - name: "Run tests"
        run: |
          docker-compose run odoo --test-enable --workers=0 --stop-after-init -d test -i web
